### ISSUE TITLE
Closed source version of pellet

### ISSUE THREAD

**Issue by fourcube** [Complexible/pellet#24]
I am currently evaluating various Java OWL reasoners for use in a project and was wondering: What are your plans regarding the open source version of pellet? Will it's development be discontinued now that there is a closed source version incorporated in your SaaS?

**Comment by kendall** [comment]
We don't have an SaaS. There is a forked Pellet incorporated into Stardog. You could use Stardog in yr project since it is also a "Java OWL reasoner"; a strict superset of Pellet.

The community is working on Pellet as it sees fit and we participate in that, too. Beyond that there aren't any hard or fast plans.

**Comment by fourcube** [comment]
Thank you for your swift response. I will definitely check out Stardog!
